version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - BOT_TOKEN=token
    volumes:
      - .:/app
    command: python main.py
